Feature: Refresh Tokens with Various Combinations

  Scenario Outline: Refresh tokens after successful login
    Given I have successfully logged in and "<refershtoken>"
    When I use the refresh token to request new tokens
    Then I should receive a <status> status code
    And the response should contain "idToken" and "accessToken" that are not empty

    Examples:
      | refershtoken                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | status |
      | eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.dz_w69I5HUs-5Y7xkvYOHA4qvp5ch4ssDop7gUW3WJOzVo8eDIY6HdmousVn9oem_BMB7TbK6SxuLUTJp_TdP9G42ub-e9rwTgM8z4eQmBts9tp9cDyZ8iOatNJ-AmqfBAWlpqaMpsDe8w5cezROsoc-EWPizhV3WWnRtvy8VvJ0xGx5TEkKtr6SlFGRbw3xpPnG4YLm3nfCOr56EZ-4J1IpAElSgsF91iKmAGMAE2OCZVdoxS6rFXidZVWUig2OzMxM5uSaTvRl0HChptzCJQdkn5nLLX0AA1xEhH5HhXu4hmRwcJohOU7DSoDbgOJTGrcJX0Et3Ah23EWoEWz20g.QFW_leyc1SOtYNe6.1NXPRZR2VoIQO1fyskllY2eRe29AVI5w9eeZAXZAwLxUZspmJHFNkFg2zKgkjcnxi0kO27pgBDnbvg1FzHJi4pZac3FELJ5xW8ztCP-oaQ29Bwo3m44AEH4XYCFP6tuJvAsqxcQ0bWebUbkqt8rjOZ74_AHcUT5Pv7QbZqC7yNNQsUHvgQd7y988oX0hG4ni_KnlXcuS-8izxjmwUnuDppyzsti6LUh-uHFDwvwQ81jYIEi4HPedGyQvoGSmvVlIcTsrZhmc_cSGzv60hDLrFawiFRAL170wPhyUJ_6aEkh4UzEcDwMgo1PgzmGMfhvJG8U8kcXupgg6uRUA0Xc_AkfOBE-kM5-92v5UYZx8Oz5v8Uke87VuHcfvf9DKcVOaXB42KEJLlmIuZ5PYomAxffZ9n932mzvV3Ag92Gihu0zg1OWJtG-xUBfDH4ve716xPTxLitnKpFl0rJtcvlaPvAKDJVGEAXhOg-_rNeFBDBcvFCsoR0XYuvz-t8-nTis_GA5RKVXFV12MvxPyJdXOAmRSdCj3rh3Dm9Ou_uAQKDafRY5G2q149L3XaKphPvRFK2GkzTHW3NisYVqBmZgRG3lwnW49gSonmF6Rog4KtOvQ0O8gImYjhCrRGBtUJm9-UdIJHqnA1dLT_58trf_WuhpwhRTFE4mcIPPCy2sb98k9t2g8OUtA1bo3FlDHLs2em9WZewpEICC1a6azT8IrZk1PmMXDSxWPSreA29dAhxDreJ0gMpyJ1RWbxFrstP9YFiUXxJzAHK1IxvqDYFgy69yzS-IS7FcUuR0e8z1imiirt2O9eqnZ3WNf2KZiSDCd1OndptvQ4AL5imD3r0fvoCClmFly6i28-9xSmHOsATKRWAk6Z-N_eZVt_1qGeBnjepb-Jt5hM64zZMvfpRSzYs4APVfTSSshgtxbRaf-y6gjVvBwLaEPoGhAufCyz4LEyEa0ThxRHDMzY-KJNpQ9qx7PHmfipG7edwQ8GcdWMply732LOr6zrcSepFeRHc8mMK63-fvMXq6LyWWAS_mbcjFcgMp43gL_aKsWOThLhkbQrBi25R2oG-ZWGhF_i3yMpcE41cHJXKuyLHrs07xxcuwRYqtkn5Lju0nuwDqt6QinrgSNL9REaz97iAkLl5eKK7SKqnSQHg9qynYzWCCQLsebBsUQ8hz4GmQC3p3iJqEvCGXvvnzsRUtuPZCAkwhwLc2JAgQHjkCwbje5nYp_CKPM1k-CdZNkqM9yzYcecr7Kz1THiEwrlYSGqRNzfwzJ03pVGPmVm__yVKopr5-zDL2XTwquXa4f8tMPdQ.Q376UTXV621ZZD-jXi1-xg | 200    |


  Scenario Outline: Invalid token refresh tests
    Given I have successfully logged in and retrieved the tokens from the previous scenario
    When I use the refresh token "<refreshToken>" to request new tokens
    Then I should receive a <status> status code
    And the response should contain the error message as "<errorMessage>"

    Examples:
      | refreshToken                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | status | errorMessage                                                                                                            |
      | eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.EDDNjPnWdN5grajVBJ5Db_xnJ_-NHKaCt-9oYaTgYeGAUtI4OabSHNmC5ak32XC4U2M0YkyyL6lbpPjzZpJNnzIo6SucQFfmgxD8tXuRJj9l9lgci4U8k_HJ56TwB4LVDCRAVPKcVI3Xl1Oa6cKFKAkPuC1CDS6vTwcZsPR0BTHcgM27m4TKnNWU4bYJKNF67aTlbHbsXKSvuPt0aslTSWk45x2nG6f9TmyvDhtKsP9XnvtKXgIV71FkztAuIYuM-W2X6_eWwymuGUZms_mkyefCaQ32aAg0Lu-fVcFH_mHwMSuQYzhRIm-X_ErykrvF6GBUrdqtsDJEI7uibWCRGg.ZFaUUsfiCca7ebcN.x6B_yn0cyhFLdvDbO4xnPdohNApZdEh136g9gKrhiycWUg9QFRN6PWqy20TrMyhzZE7LywgSljIz2D23m-LIrIH0RSBjMgoSsJ4rKev5bfUxWXUjnCfX3kYnVcmNMFr6pDCeSL9n5hGX4Zt0miQP5HfJ_7CWxSq4G_zWtm1J-UGi46dETdci-LGpSnonsrHSmVifdGFjwes4Yja1_72nku4s15dAC1_ZYs832ssWbycgrWmDREXpd5AmNEjeocxAEQqy-pTGmb55uWuCVB-Vl8pcyk-zJroU4AQAyFL2sd0La8wTM-6V5-3EjiTMFu7aUlLG0dRDatPQasmf0VrXVe4WcTn64zSRI0CHNpBkFmZiR-6IX66DME7zGPEXik6J1JJJKs9mfI_64TLfCpqW0_uOBW9eL4HK6iKthA5g0fjP9PXks9Lt4XtsExt2V4APeb6lWu6FlkX5iGpi9PaBgzhV9XSNQkPxIqP_CqXv9VOHgd2OXjIJLgSGdGlLstvCZsofPMKVqmuEer0Fo0yKvXuH0E0jKszTYNKLmiqUJfXSvJ3tXVBDNbEtuRC357WCzcLdj2Ldr26JszgVg9VZx4DSUbyBrjGBrxTWRoi6aHxHOlUdjnTRE97B9jU1M2TJGR45eIEjNNE8Uder5NSq2QBxlXQ8P64u5RszNC0q5l4vKe9oOVaaEy2ukCHgHtCDN8v0l-Ijh8ZiT055VAYGAzhSp9uN6CE-ajuvaiKEZifqDKu332cqVtyr0MF-NL-2S2jMV7xQ9J1RO6vWxNa96UqbB-C9IuYp8Q3EEE9Lh8e5zqDtMz71G0vxbGKnSmHkobWL2MJnZB5yWLk8Cm-ugEL2kXjDUv7tG0l1e8ilRiPBLQFyEbzq4b5p9WsX25fZlnYDWGRG_2I9zIdQ5lpMx59T3bA_JV6AvNYssOKseZjjuSNagj_9SkjZO5n5jEhVP_RoiPOg9zTTFgmpvVXMjUV8n14fOZ6PMIViLN3gk8O9_4pDw-iwqhsnhjM-oU-JaG7fe4MVpqer-rUl_K3srxKdU4-I3o9gBE_byChWhpsRUBUKp38GHxR6CUYe-qK4it4oNJcbaJe6YAhOcTdRAYWuEbXc8RpUcIj5eJsGGSSTPCoXR_Prcwy6E2cQ7-sI8MewvIfTDumY3vqyAGfVrqDjaE-mnuL_zFMvmFgH7e7VG2ZUDUwAcwNLGOJvahHqXNGTS2zbOOuqww0CCp0wlemahW6qXJAU0ZoPY3oD43FKoKpph_xzlfY6rCugmlzBICRVgeFqDDEURwnt-114GpeAOaQJRLQTMdlIRkxWLf9BYFgJMP92_E4UUK3fkx0._p-U2hY2BAxRMbb3d | 400    | Failed to refresh tokens: Invalid Refresh Token (Service: CognitoIdentityProvider, Status Code: 400                     |
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | 400    | Failed to refresh tokens: Missing required parameter REFRESH_TOKEN (Service: CognitoIdentityProvider, Status Code: 400, |
