Feature: User Logout Functionality

  Background: The user is logged in
    Given the Url is present in Config file
    And the user is authenticated with email and password
    And the response contains a valid id token and access token

  Scenario Outline: User attempts to log out with successful token conditions
    When I send a POST request to the logout endpoint
    Then I should receive a <statusCode> status code for logout successful
    And the response should contain the message "<message>"
    Examples:
      | statusCode | message                       |
      | 200        | User logged out successfully. |

  Scenario Outline: User attempts to log out with different token conditions
    When I send a POST request with "<idToken>" and "<accessToken>" to the logout endpoint
    Then I should receive a <statusCode> status code for logout unsuccessful
    And the response should contain the message "<message>" for unsuccessful
    Examples:
      | idToken                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | accessToken            | statusCode | message      |
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | edscdscsacdsssssssssss | 401        | Unauthorized |
      | hjedjwhdekbd                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |                        | 401        | Unauthorized |
      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |                        | 401        | Unauthorized |
      | eyJraWQiOiJCcTM5WmNnTWpkYlwvWjJRd1wvS3NmOHQ4eStcL3QwVUx0SG1SV3Z3ZVJwVnVnPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJhOTVhMjUyYy04MDIxLTcwZjItODU1YS04NGQ0MGY3YjQyZTgiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtc291dGhlYXN0LTEuYW1hem9uYXdzLmNvbVwvYXAtc291dGhlYXN0LTFfODRwZE9ucXJSIiwiY29nbml0bzp1c2VybmFtZSI6ImhlbWFAZXBhbS5jb20iLCJvcmlnaW5fanRpIjoiOTAxNGRiYWEtODBkMC00ZjY3LWJiZGEtN2UyYmVlYzgwMGU1IiwiYXVkIjoicmRmYW4zaDJlamdzcWlsbW90MWpoanM5ciIsImV2ZW50X2lkIjoiOWIyMjQ5MTktYzQ3OC00NTBlLWJlNGQtODA3MDMzM2MxZjBhIiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE3MjYwNDkwODYsImV4cCI6MTcyNjA1MjY4NiwiaWF0IjoxNzI2MDQ5MDg2LCJqdGkiOiJiNjI3Y2I2Zi01MjQwLTRkZjktODAyNS03ZmY1Yjc1Nzk3NTciLCJlbWFpbCI6ImhlbWFAZXBhbS5jb20ifQ.upoqPnJBVvUAJ9Z_8adlXfz1N1DbMPqdyIWHp_6QD296c6_w3KvHxQi2JvDozN9FE6K5gBhRyAuFHa1V2sCirzE2BEQXsRlDAa_oLdYtkAzGP4HXYX16LNjIxzbrpL0sic-5UJGbr5TyyaZFB3WO73k0gJEYgZHkiMm9wCFVsrgPlQC35TnP52PtBKkDI0HXBKnSw5oeH50iJ_J26LIOI1D0iFXWsgAEKRyxa1Z8vBicWqIvVwglYBt2eGwSDI8ybr2mlaPjrSFqWm63OmU_Sk9QAk-pjuUGO3VB92tMcWaltveDeYpjYuUVWZ0BOLbHP1_pBQzhkYnu4_LvLobg2A |                        | 400       |   1 validation error detected: Value at 'accessToken' failed to satisfy constraint: Member must satisfy regular expression pattern: [A-Za-z0-9-_=.]+ (Service: CognitoIdentityProvider, Status Code: 400,           |